### ISSUE TITLE
"Could not find module X" when running "wai-devel"

### ISSUE THREAD

**Issue by adinapoli** [urbanslug/yesod-devel#8] opened 2015-09-24 12:14 UTC
As reported in #7, with this comment: https://github.com/urbanslug/wai-devel/issues/7#issuecomment-142911517

I'm pretty sure it's not a bug but rather something either undocumented or that I ignore. In my stack project I'm getting this:

```
☁  metrics [issue-2232] ⚡ wai-devel -p app/Main.hs -f main
"app/Main.hs"
"main"
Starting devel application at http://localhost:3000
UpdateStatusRequiredRestart
UpdateStatusDone
Error: app/Main.hs@6:8-6:19 Could not find module ‘Application’
Use -v to see a list of the files searched for.
```

This is my stripped-down cabal manifest:

```
name:                metrics
version:             0.1.0.0

library
  hs-source-dirs:      src
  exposed-modules:
    Routes
    Application
  build-depends:       base
                     , Spock
                     , text
                     , transformers
                     , wai
                     , wai-middleware-static
  default-language:    Haskell2010

executable metrics
  hs-source-dirs:      app
  main-is:             Main.hs
  ghc-options:         -threaded -rtsopts -with-rtsopts=-N
  build-depends:       base
                              , metrics
                              , warp
  default-language:    Haskell2010
```

As you can see, `Application` lives in `src`.

Do I need to set the `GHC_PACKAGE_PATH` in any particular way?
Thanks!
A.

**Comment by urbanslug** [comment] 2015-09-24 12:21
No you actually don't need to set GHC_PACKAGE_PATH or anything else actually. As long as stack can build your application wai-devel should too.

Is `stack build` succeeding?

I should really just test this with spock myself. Let me set up spock and fix this. Since I have never used/tried spock this might be a while. Do you have any spock project that I can just clone and test with?

**edit**
It seems to me that ide-backend can't find your Application module. Looking at the project structure/tree you posted earlier https://github.com/urbanslug/wai-devel/issues/7#issue-108079321 I don't see an Application.hs file.

**Comment by adinapoli** [comment] 2015-09-24 12:58
`stack build` does indeed succeeds and this is my project structure at the minute:

```
☁  metrics [issue-2232] stack build
☁  metrics [issue-2232] tree
.
├── LICENSE
├── Setup.hs
├── app
│   └── Main.hs
├── metrics.cabal
├── src
│   ├── Application.hs
│   ├── Routes.hs
│   └── Types.hs
├── stack.yaml
├── static
│   └── js
│       └── jquery.min.js
└── test
    └── Spec.hs

5 directories, 10 files
```

As you can see, there is the Application module in `src/Application`. I suspect then there is a problem with `ide-backend` and it is somehow looking at the global package manifest instead of the local one? Is that even possible?

**Comment by urbanslug** [comment] 2015-09-24 13:03
Yes I also suspect that it's an issue with how ide-backend looks for files when TargetsInclude is used (but it can be fixed from within wai-devel side I believe, maybe I'm not passing files to ide-backend as it expects). I have looked at starting up a spock project and it seems there's no default scaffold for spock. Could you zip your current project and provide a download link or upload it to github for me to work on please?

**Comment by adinapoli** [comment] 2015-09-24 13:10
Here we go: https://www.dropbox.com/s/g94lo42ntljq42t/spock-test.zip?dl=0

Is not an exact replica of the project I'm mentioned but should be good enough to get you up & running and reproduce the problem (or the lack thereof) successfully. 

Thanks for looking into this!

**Comment by urbanslug** [comment] 2015-09-24 13:18
@adinapoli If I haven't solved it by tomorrow I shall have to wait until after Monday for me to continue work on it because I shall be very busy from after tomorrow. Please be patient.

You're the one helping me get wai-devel to work smoothly across various Haskell web frameworks. Don't thank me :smile_cat: Thank you.

**Comment by adinapoli** [comment] 2015-09-24 13:20
Seems like a win-win scenario then :wink: 

Sure, no pressure, it's free software, so work on it whenever you have time/will ;)

A.

**Comment by urbanslug** [comment] 2015-10-01 13:27
@adinapoli 
Hello, I believe I have a solution for this. Why not go ahead and pull tell me what you think and maybe we can close this issue. Also for some better output with wai-devel I thought this would be good as your Main.hs but again I don't know what the spock culure is.

``` haskell
{-# LANGUAGE OverloadedStrings #-}

module Main where

import qualified Network.Wai.Handler.Warp as Warp
import Application
import System.Environment (lookupEnv)

main :: IO ()
main = do 
  mPort <- lookupEnv "PORT"
  let port = case mPort of
               Just p -> read p :: Int
               _ -> 8080
  app >>= Warp.run port
```

run as

``` zsh
$ PORT=8080 wai-devel -p app/Main.hs -f main
```

or you can set the environment variable PORT if you wish.

Anyway, tell me what you think.

**Comment by adinapoli** [comment] 2015-10-02 07:47
Hey,

I had to delete this line from your cabal manifest to make the project compile:

https://github.com/urbanslug/wai-devel/blob/master/wai-devel.cabal#L29

Apart from that now `wai-devel` starts, but I see this suspicious output at startup:

```
Starting devel application at http://localhost:3000
UpdateStatusRequiredRestart
KindServerDied
```

(I'm referring to the `KindServerDied`). When I try to modify 1 file, save it and watch for changes this is what I see:

```
wai-devel: /Users/adinapoli/work/athena/metrics/src/.#HTTP.hs: getFileStatus: does not exist (No such file or directory)
wai-devel: /Users/adinapoli/work/athena/metrics/src/.#HTTP.hs: getFileStatus: does not exist (No such file or directory)
```

Unfortunately this is due (I think) to the fact `wai-devel` watches for all the files, and Emacs, when you are editing (but not saving) a file will create this intermediate files with the `#` in them. I suspect you weren't hit by this as you are using a different editor?

**Comment by urbanslug** [comment] 2015-10-02 19:37
Yeah that line in the cabal file was there by accident. I have so many branches that I try different things on and sometimes forget to check out, sorry.

When the environment variable PORT isn't set wai-devel assumes you want to use port 3000. You can fix this by setting an environment variable PORT or by preceding wai-devel with PORT e.g `PORT=8080 wai-devel -p ...`  If you don't like how one uses is forced to use PORT could you recommend a different approach that you believe is more favourable? I believe all should be working well now except for one annoying issue I shall explain below.

## File watching

The file watching should be working now but changes in Template Haskell files won't trigger a proper recompile as expected so I have removed this for the moment to avoid confusing the user with misleading output that a proper recompile has taken place. One has to mutate the file calling the TH file to see the change applied but that isn't the matter here.

**Comment by urbanslug** [comment] 2015-10-09 02:23
@adinapoli I believe all things are okay now. Planning to release this on hackage.

**Comment by parsonsmatt** [comment] 2015-10-09 16:18
I'm getting the same (or similar) issue with this repository: https://github.com/parsonsmatt/QuickLift

``` bash
λ stack build
λ  wai-devel -p app/Main.hs -f main
Starting devel application at http://localhost:3000
UpdateStatusRequiredRestart
UpdateStatusDone
Error: src/Parser.hs@6:18-6:39 Could not find module ‘Text.Megaparsec.Lexer’
Use -v to see a list of the files searched for.
Error: src/Parser.hs@5:8-5:23 Could not find module ‘Text.Megaparsec’
Use -v to see a list of the files searched for.
```

Commenting out the `Parser` module fixes it. `megaparsec` is being installed as an `extra-deps`. Could there be an issue where wai-devel or ide-backend-server isn't seeing the extra-deps?

If this seems to be unrelated I can open another issue :)

**Comment by urbanslug** [comment] 2015-10-09 23:33
I haven't reproduced the issue yet but it seems we should have a separate issue for wai-devel not finding packages installed as extra-deps since it ca find packages installed elsehow.

**Comment by parsonsmatt** [comment] 2015-10-09 23:43
Sure thing! I'll open a separate issue.

**Closed as completed** 2015-10-25 19:17 UTC
